#!/usr/bin/env node
/* Builds server/src/simgame.js from the game file: the game's own code, run
   by the room server as the match host. Same ball, same bots, same abilities,
   same hits -- nothing re-written, so the server can never disagree with the
   game about the rules.

     node server/tools/buildsim.cjs            (from the repo root)

   It takes the game's main <script>, wraps it in a function that is handed a
   headless stand-in for the browser (see sim.js), and adds one hook at the
   end so the server can reach the handful of things it drives. Run it after
   every change to the game, like gencatalog. */
const fs = require("fs"), path = require("path");
const ROOT = path.resolve(__dirname, "..", "..");
const GAME = path.join(ROOT, "site", "index.html");
const OUT = path.join(ROOT, "server", "src", "simgame.js");
const src = fs.readFileSync(GAME, "utf8");

const at = src.indexOf("<script>\n(function(){");
if (at < 0) throw new Error("the game's main script was not found");
let body = src.slice(at + 8, src.indexOf("</script>", at));
const end = body.lastIndexOf("})();");
if (end < 0) throw new Error("the game's script does not end the way it should");

// the few things the server drives, and the one function it replaces (netSend)
const HOOK = `
__G.hook({
  NET: NET,
  frame: frame,
  netHandle: netHandle,
  setSend: function(fn){ netSend = fn; },
  get: function(){ return { STATE: STATE, fighters: fighters, balls: balls, player: player, gameT: gameT, MODE: MODE }; },
  living: function(){ return livingFighters(false); },
  reset: function(){ riftAbort(); NET.on = false; clearFighters(); clearBalls(); STATE = "venue"; },
  // what the START button does, minus everything on screen: the save, the
  // shared meshes and materials, the particle pools. Lowest quality: the
  // server draws nothing, so it spawns as few effects as the game allows.
  boot: function(){ loadSave(); QUAL = 0; buildTextures(); initAssets(); initParticles(); STATE = "venue"; },
  maps: function(){ return MAPS.map(function(m){ return m.id; }); },
  version: VERSION
});
`;
body = body.slice(0, end) + HOOK + body.slice(end);

// browser globals the game reaches for, handed in by sim.js instead
const GLOBALS = ["window", "document", "navigator", "location", "localStorage", "performance", "requestAnimationFrame",
  "cancelAnimationFrame", "Image", "Audio", "AudioContext", "fetch", "WebSocket", "alert", "confirm", "prompt",
  "innerWidth", "innerHeight", "devicePixelRatio", "getComputedStyle", "matchMedia", "addEventListener",
  "removeEventListener", "google", "history", "screen", "Blob", "URL", "self", "setTimeout", "setInterval",
  "clearTimeout", "clearInterval", "THREE", "BAKED_MUSIC", "Event", "KeyboardEvent", "HTMLElement", "atob", "btoa"];

const out = "// GENERATED by server/tools/buildsim.cjs from site/index.html. Do not edit by hand.\n" +
  "/* eslint-disable */\n" +
  "export function bootGame(__G) {\n" +
  GLOBALS.map(g => "  const " + g + " = __G.env." + g + ";").join("\n") + "\n" +
  body + "\n}\n";
fs.writeFileSync(OUT, out);
console.log("wrote", path.relative(ROOT, OUT), "-", Math.round(out.length / 1024) + " KB");
